In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from statsmodels.tsa.stattools import adfuller

In [23]:
data_new_worth = pd.read_csv("/content/net_worth_cleaned.csv", encoding='ISO-8859-1')
data_unemployment = pd.read_csv("/content/unemployment_cleaned.csv", encoding='ISO-8859-1')

In [27]:
data_new_worth.index = pd.to_datetime(data_new_worth.index)
data_unemployment.index = pd.to_datetime(data_unemployment.index)

data_new_worth, data_unemployment = data_new_worth.align(data_unemployment, join='inner', axis=0)

data_new_worth = data_new_worth.asfreq('QS')
data_unemployment = data_unemployment.asfreq('QS')

In [28]:
model_fits = {}
for y_col in data_new_worth.columns:
    for x_col in data_unemployment.columns:
        y = data_new_worth[y_col].dropna()
        X = data_unemployment[[x_col]].loc[y.index]
        try:
            model = ARIMA(y, exog=X, order=(1,1,1))
            model_fit = model.fit()
            model_fits[(y_col, x_col)] = model_fit
            print(f"Fitted: {y_col} ~ {x_col}")
        except Exception as e:
            print(f"Skipped {y_col} ~ {x_col}: {e}")

Skipped observation_date ~ observation_date: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Skipped observation_date ~ 20-24: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Skipped observation_date ~ 25-34: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Skipped observation_date ~ 35-44: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Skipped observation_date ~ 45-54: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Skipped observation_date ~ 55 & Over: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Skipped 99.9% to 100% ~ observation_date: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Fitted: 99.9% to 100% ~ 20-24
Fitted: 99.9% to 100% ~ 25-34
Fitted: 99.9% to 100% ~ 35-44
Fitted: 99.9% to 100% ~ 45-54
Fitted: 99.9% to 100% ~ 55 & Over
Skip

/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/mlemodel.py:1235: RuntimeWarning: invalid value encountered in divide
  np.inner(score_obs, score_obs) /
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/mlemodel.py:1235: RuntimeWarning: invalid value encountered in divide
  np.inner(score_obs, score_obs) /
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/sarim

Fitted: 99% to 100% ~ 25-34
Fitted: 99% to 100% ~ 35-44
Fitted: 99% to 100% ~ 45-54
Fitted: 99% to 100% ~ 55 & Over
Skipped 90% to 99% ~ observation_date: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Fitted: 90% to 99% ~ 20-24
Fitted: 90% to 99% ~ 25-34
Fitted: 90% to 99% ~ 35-44
Fitted: 90% to 99% ~ 45-54
Fitted: 90% to 99% ~ 55 & Over
Skipped 50% to 90% ~ observation_date: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Fitted: 50% to 90% ~ 20-24
Fitted: 50% to 90% ~ 25-34
Fitted: 50% to 90% ~ 35-44
Fitted: 50% to 90% ~ 45-54
Fitted: 50% to 90% ~ 55 & Over
Skipped 0% to 50% ~ observation_date: Pandas data cast to numpy dtype of object. Check input data with np.asarray(data).
Fitted: 0% to 50% ~ 20-24
Fitted: 0% to 50% ~ 25-34
Fitted: 0% to 50% ~ 35-44
Fitted: 0% to 50% ~ 45-54
Fitted: 0% to 50% ~ 55 & Over


/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/mlemodel.py:1235: RuntimeWarning: invalid value encountered in divide
  np.inner(score_obs, score_obs) /
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/sarimax.py:866: UserWarning: Too few observations to estimate starting parameters for ARMA and trend. All parameters except for variances will be set to zeros.
  warn('Too few observations to estimate starting parameters%s.'
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/mlemodel.py:1235: RuntimeWarning: invalid value encountered in divide
  np.inner(score_obs, score_obs) /
/usr/local/lib/python3.12/dist-packages/statsmodels/tsa/statespace/sarim

In [29]:
predictions = {}
for (y_col, x_col), model_fit in model_fits.items():
    last_val = data_unemployment[x_col].iloc[-1]
    future_X = pd.DataFrame({x_col: [last_val]*5})
    try:
        forecast = model_fit.forecast(steps=5, exog=future_X)
        predictions[(y_col, x_col)] = forecast
    except Exception as e:
        print(f"Forecast failed for {y_col} ~ {x_col}: {e}")

In [31]:
for (y_col, x_col), pred in predictions.items():
    print(f"{y_col} predicted by {x_col}:")
    print(pred.values)

99.9% to 100% predicted by 20-24:
[8459950. 8459950. 8459950. 8459950. 8459950.]
99.9% to 100% predicted by 25-34:
[8459950. 8459950. 8459950. 8459950. 8459950.]
99.9% to 100% predicted by 35-44:
[8459950. 8459950. 8459950. 8459950. 8459950.]
99.9% to 100% predicted by 45-54:
[8459950. 8459950. 8459950. 8459950. 8459950.]
99.9% to 100% predicted by 55 & Over:
[8459950. 8459950. 8459950. 8459950. 8459950.]
99% to 99.9% predicted by 20-24:
[1271227. 1271227. 1271227. 1271227. 1271227.]
99% to 99.9% predicted by 25-34:
[1271227. 1271227. 1271227. 1271227. 1271227.]
99% to 99.9% predicted by 35-44:
[1271227. 1271227. 1271227. 1271227. 1271227.]
99% to 99.9% predicted by 45-54:
[1271227. 1271227. 1271227. 1271227. 1271227.]
99% to 99.9% predicted by 55 & Over:
[1271227. 1271227. 1271227. 1271227. 1271227.]
99% to 100% predicted by 20-24:
[18457391. 18457391. 18457391. 18457391. 18457391.]
99% to 100% predicted by 25-34:
[18457391. 18457391. 18457391. 18457391. 18457391.]
99% to 100% predict